---
- name: Test condition
  hosts: tomcatServers
  remote_user: root

  vars:
    # string
    vm1: "68.183.51.116"
    vm2: "159.65.250.43"
    #boolean
    run_task: true

  tasks:
#  - debug: msg="output is {{ansible_all_ipv4_addresses}}"
  - name: Run task on VM1
    command: ifconfig
    register: output
    when: ansible_all_ipv4_addresses[1]==vm1
  - debug: msg="The Output is {{output}}"

  - name: will this task run or not
    when: run_task and ansible_all_ipv4_addresses[1]==vm1
    shell: echo "Hey, I am running else not"
    register: output
  - debug: msg="{{output.changed}}"

#  - fail: msg="mytask needs my_task varibles to set"
#    when: my_task is undefined

