---
- name: Test filters
#  hosts: "{{tomcat_hosts | default('tomcatServers')}}"
  hosts: tomcatServers
  remote_user: root
  become: yes

  vars:
    cheese: ['american', 'cheddar', 'cheddar', 'mozzarella', 'bleu', 'manchego', 'mozzarella']
    pizza_toppings: ['mozzarella', 'anchovies', 'pineapple', 'bleu', 'pepperoni', 'mushrooms']
    
  tasks:
  - name: quick echo
    shell: echo $PATH
    register: result

  - debug: msg="{{cheese | unique}}"

  - debug: msg="{{cheese | difference(pizza_toppings)}}"

  - debug: msg="{{cheese | union(pizza_toppings)}}"
#
#  - shell: /usr/bin/foo
#    register: result
#    ignore_errors: True
#
#  - debug: msg="it failed"
#    when: result is failed
#
#  # in most cases you'll want a handler, but if you want to do something right now, this is nice
#  - debug: msg="it changed"
#    when: result is changed
#
#  - debug: msg="it succeeded"
#    when: result is success
#
#  - debug: msg="it was skipped"
#    when: result is skipped
