---
- name: Test filters
#  hosts: "{{tomcat_hosts | default('tomcatServers')}}"
  hosts: tomcatServers
  remote_user: root
  become: yes

  vars:
  
    cheese: ['american', 'cheddar', 'cheddar', 'mozzarella', 'bleu', 'manchego', 'mozzarella']
    pizza_toppings: ['mozzarella', 'anchovies', 'pineapple', 'bleu', 'pepperoni', 'mushrooms']
    
  tasks:
  - name: quick echo
    shell: echo $PATH
    register: result

  - debug: msg="{{cheese | unique}}"

  - debug: msg="{{cheese | difference(pizza_toppings)}}"

  - debug: msg="{{cheese | union(pizza_toppings)}}"
