- name: Test loops
  hosts: tomcatServers
  remote_user: root
  become: yes

  tasks:
    - name: Create new users
      user:
        name: '{{ item }}'
        state: present
      loop:
        - amza
        - oghenekaro
        - Don
        - francis
        - blaise
#      loop_control:
#        pause: 3
