- name: Test loops
  hosts: tomcatServers
  remote_user: root
  become: yes

  tasks:
    - name: Create new users
      user:
        name: '{{ item }}'
        state: present
      loop:
        - john
        - mike
        - andrew
      loop_control:
        pause: 2
