---
- name: Get User info
  hosts: tomcatServers
  remote_user: root
  vars:
    name: "jashan"
  vars_files:
    - my_vars.yaml

  tasks:

  - debug: msg="My name is {{name}}"
  - debug: msg="My occupation is {{occupation}}"
